### ISSUE TITLE
OTF variant?

### ISSUE THREAD

**Issue by HolbyFPV** [Templarian/MaterialDesign-Font#10]
I have a project that has bugs with .ttf fonts, but can process OTF fonts just fine.  Can we get a OTF variant of this lovely icon set?

**Comment by Templarian** [comment]
@notblam Slowly trying to rewrite our font build script based on a OTF format (starting with the new [Memory set](https://pictogrammers.com/library/memory/)), but this is going to take a bit. Until then I would use a free online service.

**Comment by HolbyFPV** [comment]
> @notblam Slowly trying to rewrite our font build script based on a OTF format (starting with the new [Memory set](https://pictogrammers.com/library/memory/)), but this is going to take a bit. Until then I would use a free online service.

Awesome.  I'll be looking forward to hearing how this goes.
