### ISSUE TITLE
Add an extra JSON cheatsheet

### ISSUE THREAD

**Issue by attisan** [Templarian/MaterialDesign-Font#3]
Would it be possible to add a cheatsheet.json file containing a name to hex code map / object? I would guess, it doesn't need to contain the actual SVG payload (in contrast to the current cheatsheet.html).

If it would be all the same to you, it would also be interesting having header-files for programming languages (c++, c, c# ... as it is provided for other fonts by [IconFontCppHeaders](https://github.com/juliettef/IconFontCppHeaders) who's script [isn't compatible with MDI anymore](https://github.com/juliettef/IconFontCppHeaders/commit/ed95358efe71645cb810a6e3e4c1ea7efc8eaadb)).

never mind closing the issue if either ideas are out of scope.

**Comment by Templarian** [comment]
You can use the `meta.json` for this. It's explained here:

https://dev.materialdesignicons.com/contribute/third-party-guide

https://dev.materialdesignicons.com/guide/nodejs-scripting
