### ISSUE TITLE
Font is not picked up by Xorg

### ISSUE THREAD

**Issue by h4ckee** [Templarian/MaterialDesign-Font#4]
Hello.
The font is not get recognized by xorg server.
Usually Xorg creates an index of scalable font files by running `mkfontscale` and `mkfontdir`.
`mkfontscale` reads all of the scalable font files in the directory.  For every font file found, an X11 font name is generated, and is written together with the file name to a file fonts.scale in the directory. `mkfontdir` writes to 
fonts.dir file.
In my case nothing is being written and so the font is not get recognized by xorg server.

> ll
total 1008K
-rw-r--r-- 1 x users 1005K мар  5 20:55 MaterialDesignIconsDesktop.ttf
> mkfontscale 
> mkfontdir
> ll
total 1016K
-rw-r--r-- 1 x users 1005K мар  5 20:55 MaterialDesignIconsDesktop.ttf
-rw-r--r-- 1 x users     2 мар  5 21:01 fonts.dir
-rw-r--r-- 1 x users     2 мар  5 21:01 fonts.scale
> cat fonts.*
0
0

The old version of the MaterialDesign-Webfont file 4.9.95 works as expected and is recognized by xorg server:
> cat fonts.dir
57
...
materialdesignicons-webfont.ttf -misc-material design icons-medium-r-normal--0-0-0-0-p-0-iso10646-1
> cat fonts.scale 
57
...
materialdesignicons-webfont.ttf -misc-material design icons-medium-r-normal--0-0-0-0-p-0-iso10646-1

**Comment by Templarian** [comment]
It's because we moved all the codepoints into the unassigned F0001-* indexes for v5+. That might be messing with that script.

There is probably nothing we can do to fix this unfortunately. Possibly see if converting it to another format works. There are several sites to convert the TTF.

**Comment by h4ckee** [comment]
Understood thanks.
